name: Laravel Docker CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set up Docker environment
      - name: Set Up Docker
        run: |
          docker --version
          docker compose version

      # 3. Build and Start Services
      - name: Build and Start Containers
        run: |
          docker compose up -d --build
          docker compose ps

      # 4. Run Composer Install
      - name: Install Composer Dependencies
        run: |
          docker compose run --rm composer install

      # 5. Run Artisan Migrations
      - name: Run Migrations
        run: |
          docker compose run --rm artisan migrate --force

      # 6. Run Laravel Tests
      - name: Run Laravel Tests
        run: |
          docker compose run --rm artisan test

      # 7. Tear Down Containers
      - name: Tear Down Containers
        run: |
          docker compose down --remove-orphans -v
