name: Laravel CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Verify Docker tooling
      - name: Verify Docker Tooling
        run: |
          docker info
          docker version
          docker compose version

      - name: Verify SSH Connection to Server
        uses: appleboy/ssh-action@v0.1.8
        with:
            host: ${{ secrets.UBUNTU_VM_IP }}
            username: ${{ secrets.UBUNTU_VM_USER }}
            key: ${{ secrets.UBUNTU_VM_PRIVATE_KEY }}
            command: whoami


      # Clear all running Docker containers
      - name: Clear All Running Docker Containers
        run: |
          docker rm -f $(docker ps -a -q) || echo "No running container to clear up..."

      # Start Docker containers
      - name: Start Docker
        run: |
          make up
          docker compose ps

      # Run Composer install
      - name: Run Composer Install
        run: |
          docker compose run --rm composer install

      # Populate .env file
      - name: Populate .env File
        run: |
          cp .env /var/lib/jenkins/workspace/envs/laravel-test

      # Run Tests
      - name: Run Tests
        run: |
          docker compose run --rm artisan test

      # Create an artifact
      - name: Create Artifact
        run: |
          cd "/var/lib/jenkins/workspace/LaravelTest"
          rm -rf artifact.zip
          zip -r artifact.zip . -x "*node_modules**"

      # Deploy Artifact to Ubuntu VM
      - name: Deploy Artifact to Ubuntu VM
        uses: appleboy/scp-action@v0.1.3
        with:
          source: /var/lib/jenkins/workspace/LaravelTest/artifact.zip
          target: ${{ secrets.UBUNTU_VM_USER }}@${{ secrets.UBUNTU_VM_IP }}:/home/${{ secrets.UBUNTU_VM_USER }}/artifact
          key: ${{ secrets.UBUNTU_VM_PRIVATE_KEY }}

      # Unzip artifact and update permissions on Ubuntu VM
      - name: Unzip and Update Permissions on Ubuntu VM
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.UBUNTU_VM_IP }}
          username: ${{ secrets.UBUNTU_VM_USER }}
          key: ${{ secrets.UBUNTU_VM_PRIVATE_KEY }}
          script: |
            unzip -o /home/${{ secrets.UBUNTU_VM_USER }}/artifact/artifact.zip -d /var/www/html
            sudo chmod 777 /var/www/html/storage -R || echo "Some file permissions could not be updated."


      # Tear down Docker
      - name: Tear Down Docker
        run: |
          docker compose down --remove-orphans -v
          docker compose ps



