name: Laravel Docker CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set up Docker environment
      - name: Set Up Docker
        run: |
          docker --version
          docker compose version

      # 3. Build and Start Containers
      - name: Build and Start Containers
        run: |
          docker compose up -d --build
          docker compose ps

      # 4. Fix Ownership and Permissions
      - name: Fix File Ownership and Permissions
        run: |
          docker compose exec php chown -R www-data:www-data /var/www/html
          docker compose exec php mkdir -p /var/www/html/vendor && \
          docker compose exec php chown -R www-data:www-data /var/www/html/vendor

      # 5. Configure Git Safe Directory
      - name: Configure Git Safe Directory
        run: |
          docker compose exec php git config --global --add safe.directory /var/www/html

      # 6. Run Composer Install
      - name: Install Composer Dependencies
        run: |
          docker compose run --rm composer install

      # 7. Run Artisan Migrations
      - name: Run Migrations
        run: |
          docker compose run --rm artisan migrate --force

      # 8. Run Laravel Tests
      - name: Run Laravel Tests
        run: |
          docker compose run --rm artisan test

      # 9. Tear Down Containers
      - name: Tear Down Containers
        run: |
          docker compose down --remove-orphans -v
