name: Build and Test Laravel App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Start Docker containers
      - name: Start Docker Containers
        run: |
          docker compose up -d
          docker compose ps

      # Install Composer dependencies
      - name: Install Composer Dependencies
        run: |
          docker compose exec app composer install

      # Run Artisan tests
      - name: Run Laravel Tests
        run: |
          docker compose exec app php artisan test
