name: Laravel Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mariadb:10.6
        env:
          MYSQL_DATABASE: homestead
          MYSQL_USER: homestead
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - 3307:3306  # Changez le port 3306 vers 3307
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root -psecret"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

      redis:
        image: redis:alpine
        ports:
          - 6380:6379  # Changez le port 6379 vers 6380
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Stop and remove existing containers
        run: |
          docker ps -aq --filter "name=redis" | xargs --no-run-if-empty docker stop
          docker ps -aq --filter "name=mysql" | xargs --no-run-if-empty docker stop
          docker ps -aq --filter "name=redis" | xargs --no-run-if-empty docker rm
          docker ps -aq --filter "name=mysql" | xargs --no-run-if-empty docker rm

      - name: Build Docker images
        run: docker-compose -f docker-compose.yml build

      - name: Run Laravel dependencies
        run: |
          docker-compose -f docker-compose.yml up -d
          docker-compose exec php composer install
          docker-compose exec php php artisan migrate --force

      - name: Run tests
        run: docker-compose exec php php artisan test
